const attendanceStore=JSON.parse(localStorage.getItem('ik_attendance')||'{}');
const attMonth=()=>new Date().toISOString().slice(0,7);
function __ikAttendanceOvertime(month=attMonth()){let total=0;Object.entries(attendanceStore).forEach(([k,v])=>{if(k.startsWith(month+'-')&&k.endsWith('-fazla'))total+=Number(v)||0});return total}
window.__ikAttendanceOvertime=__ikAttendanceOvertime;
function attendance(){
  $('#page-title').textContent='Puantaj ve Devam'; const month=attMonth(), days=30, normalCodes=['A','B','C','D','E','F','M','AB','G','Y','O','Ü','Ö','ÇRT','ÇRT.','RT','RT.','ÇHT','DV','UZ','R.','R']; const key=(id,d,type)=>`${month}-${id}-${d}-${type}`;
  const normalOptions=(id,d)=>normalCodes.map(s=>`<option ${attendanceStore[key(id,d,'normal')]===s?'selected':''}>${s}</option>`).join(''); const extraOptions=(id,d)=>['0.5','1','1.5','2','2.5','3'].map(s=>`<option value="${s}" ${String(attendanceStore[key(id,d,'fazla')]||'')===s?'selected':''}>${s}</option>`).join('');
  const rows=state.employees.flatMap(e=>[`<tr><td rowspan="2" class="att-person"><strong>${e.name}</strong><small class="muted" style="display:block">${e.department}</small></td><td class="att-type normal">Normal</td>${Array.from({length:days},(_,i)=>`<td><select class="att-select" data-key="${key(e.id,i+1,'normal')}"><option value="">—</option>${normalOptions(e.id,i+1)}</select></td>`).join('')}</tr>`,`<tr><td class="att-type extra">Fazla Mesai</td>${Array.from({length:days},(_,i)=>`<td><select class="att-select" data-key="${key(e.id,i+1,'fazla')}"><option value="">—</option>${extraOptions(e.id,i+1)}</select></td>`).join('')}</tr>`]).join('');
  $('#app').innerHTML=`<div class="section-title"><div><h2>Puantaj ve devam</h2><span class="muted">${month} dönemi · Her çalışan için normal ve fazla mesai satırı</span></div><button class="btn" id="att-save">Kaydet</button></div><div class="card att-card"><div class="att-scroll"><table class="att-table"><thead><tr><th>Çalışan</th><th>Çalışma tipi</th>${Array.from({length:days},(_,i)=>`<th>${i+1}</th>`).join('')}</tr></thead><tbody>${rows||'<tr><td colspan="32" class="empty">Çalışan bulunmuyor</td></tr>'}</tbody></table></div></div><div class="formula" style="margin-top:18px"><strong>Fazla mesai:</strong> Günlük katsayılar (0,5–3) tablodan alınır ve ücret hesaplamasına aktarılır.<br><small>Normal satırında durum, Fazla satırında katsayı seçilir.</small></div>`;
  $('#att-save').onclick=()=>{document.querySelectorAll('.att-select').forEach(s=>{if(s.value)attendanceStore[s.dataset.key]=s.value;else delete attendanceStore[s.dataset.key]});localStorage.setItem('ik_attendance',JSON.stringify(attendanceStore));toast('Puantaj kaydedildi')};
}
shell();
